# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

# Flutter төслийн script-ийг зааж өгнө.
flutter_application_path = File.expand_path('..', __FILE__)
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Flutter-ийн Pod-уудыг суулгах
  flutter_install_all_ios_pods(flutter_application_path)
end

