// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNRvtzqUtXJk9h3r9qqJJxvTGomzl1e18',
    appId: '1:690811497989:web:1747108aaf4245beb3b66c',
    messagingSenderId: '690811497989',
    projectId: 'fir-flutter-codelab-6085e',
    authDomain: 'fir-flutter-codelab-6085e.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-6085e.firebasestorage.app',
    measurementId: 'G-VETSHLEEL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAppkDmVOxAGD5b0Z7FRPl113k_Nef_GVw',
    appId: '1:690811497989:android:637564c61eeb0602b3b66c',
    messagingSenderId: '690811497989',
    projectId: 'fir-flutter-codelab-6085e',
    storageBucket: 'fir-flutter-codelab-6085e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk6o-pFUWYkNcjeS3liO_3qfazHvR2O7s',
    appId: '1:690811497989:ios:2a8deeccb856b42db3b66c',
    messagingSenderId: '690811497989',
    projectId: 'fir-flutter-codelab-6085e',
    storageBucket: 'fir-flutter-codelab-6085e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk6o-pFUWYkNcjeS3liO_3qfazHvR2O7s',
    appId: '1:690811497989:ios:2a8deeccb856b42db3b66c',
    messagingSenderId: '690811497989',
    projectId: 'fir-flutter-codelab-6085e',
    storageBucket: 'fir-flutter-codelab-6085e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNRvtzqUtXJk9h3r9qqJJxvTGomzl1e18',
    appId: '1:690811497989:web:b274677b44ab99cdb3b66c',
    messagingSenderId: '690811497989',
    projectId: 'fir-flutter-codelab-6085e',
    authDomain: 'fir-flutter-codelab-6085e.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-6085e.firebasestorage.app',
    measurementId: 'G-EVH9YKCLV4',
  );
}
